// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl3pCtfQJsL07RmyVP7xxuyxDBNHdxZhw',
    appId: '1:198002771083:android:e15a5d747094916372008e',
    messagingSenderId: '198002771083',
    projectId: 'shipped-963da',
    databaseURL: 'https://shipped-963da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shipped-963da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbiDR1CD6_3Rr7GEyCgqIKxwO9AjQt1ZQ',
    appId: '1:198002771083:ios:34b73a9d0e117d3572008e',
    messagingSenderId: '198002771083',
    projectId: 'shipped-963da',
    databaseURL: 'https://shipped-963da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shipped-963da.firebasestorage.app',
    iosClientId: '198002771083-ect6uahlapd378tgeccr79nuufggrpkn.apps.googleusercontent.com',
    iosBundleId: 'com.anmka.elemam',
  );
}
